dbt_course:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: sd96455.us-central1.gcp
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: student__b_role
      database: dev
      # Add your username to the schema name!!!
      schema: dbt_ci_oleg
      warehouse: student_wh
    prod:
      type: snowflake
      account: sd96455.us-central1.gcp
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: student__b_role
      database: dev
      schema: dbt_prod_oleg
      warehouse: student_wh
