models:
  - name: product_info
    description: ""
    columns:
      - name: product_id
        data_type: number
        description: ""

      - name: product_name
        data_type: varchar
        description: ""

      - name: category_name
        data_type: varchar
        description: ""

      - name: supplier_name
        data_type: varchar
        description: ""

      - name: units_in_stock
        data_type: number
        description: ""

      - name: units_on_order
        data_type: number
        description: ""

      - name: discontinued
        data_type: boolean
        description: ""

      - name: times_ordered
        data_type: number
        description: ""

      - name: gross_sales
        data_type: number
        description: ""
