name: dbt Production run

on:
  workflow_dispatch: # This event allows you to run the workflow manually

permissions:
  contents: read

env:
  DBT_USER: ${{ secrets.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

jobs:
  run-production-pipeline:
    name: Run dbt prodution pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Install dbt pakages
        working-directory: ./dbt_course
        run: dbt deps --target ci

      - name: Copy dbt profiles
        run: mkdir ~/.dbt && cp .github/profiles.yml ~/.dbt/profiles.yml

      - name: Lint SQL files
        run: sqlfluff lint

      - name: Create dbt seeds
        working-directory: ./dbt_course
        run: dbt seed --target prod
      
      - name: Run dbt project in CI target
        working-directory: ./dbt_course
        run: dbt run --target prod
      
      - name: Run dbt tests
        working-directory: ./dbt_course
        run: dbt test --target prod
